version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rakaadli
      POSTGRES_PASSWORD: qawsedrf
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: HAHA@GMAIL.COM
      PGADMIN_DEFAULT_PASSWORD: HAHA
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  pgadmin:
    driver: bridge

volumes:
  postgres:
  pgadmin: